Repository strapi/pack-up, pull requests merged in 2024-10, with the labels that each got.

#12 fix: check for nullish prop instead of falsy
  .changeset/smart-months-provide.md
  src/node/core/config.ts
Labels: pr: fix

#17 chore: update packages to resolve package security audits
  .changeset/three-snails-suffer.md
  package.json
  pnpm-lock.yaml
  src/node/check.ts
  src/node/core/pkg.ts
  src/node/createBuildContext.ts
  src/node/init.ts
  src/node/tasks/index.ts
Labels: pr: security

#18 fix: add permissions to the release workflow
  .github/workflows/release.yml
Labels: pr: chore

#20 fix: publishing to npm
  .github/workflows/release.yml
Labels: pr: fix
